### ISSUE TITLE
Serialized types get mixed

### ISSUE THREAD

**Issue by Rochet2** [bakpakin/binser#1]
I was using most likely https://github.com/bakpakin/binser/commit/b40334801b96de9cbb87bfb5cdaa428b71c4184f
The serialized and deserialized values are a bit different, though this is nothing that important.

```lua
local binser = require("binser")
local tbl = {1/0, 0/0, -(1/0), -(0/0), math.huge, -math.huge}
local data = binser.deserialize(binser.serialize(tbl))
print(table.unpack(data))
print(table.unpack(tbl))

-- output:
inf     -nan(ind)       -inf    -nan(ind)       inf     -inf
inf     -nan(ind)       -inf    nan             inf     -inf
```

A similar issue was fixed here: https://github.com/gvx/Smallfolk/pull/3

ps. I dont suppose its a one line change to make `\0`not appear in the serialized sequence?
Assuming it does appear in it.
Otherwise Ill encode the output string not to be able to represent the null character.

**Comment by bakpakin** [comment]
I don't know what version of Lua you're using, but I for the life of me cannot figure out how to print negative and positive nans. If there is some inconsistency, its probably in the `number_to_str` function or `number_from_str` function, which have only one corner case for nan. From your output, the binary sequence it is generating must correspond to -nan(ind).

It might be helpful to let me know which version of Lua you are using, or what platform you are on.

**Comment by Rochet2** [comment]
I used lua 5.2.3 on windows 10.

**Comment by bakpakin** [comment]
I'm closing this issue. I can't imagine any practical use for differentiating NaNs.Further more, Lua, like most languages, operates under the assumption the NaN ~= NaN following the IEEE-754 standard. If you need to differentiate, reopen the issue.
