### ISSUE TITLE
Add a version field

### ISSUE THREAD

**Issue by mpeterv** [bakpakin/binser#13]
It would be nice to have a field (e.g. `binser.version = "0.0-6"`) so that programs depending on binser could show its version in their `--version` message. This makes it easy to identify user environment when investigating issues.

(Side note: IIRC rockspec revisions are supposed to be for metadata/dependency/build instruction updates and should not point to different sources, perhaps something semver-like could be used like 0.0.6?)

**Comment by bakpakin** [comment]
Addressed finally in 0.0-8. `binser.VERSION` gets the version string.
