### ISSUE TITLE
resource example

### ISSUE THREAD

**Issue by mokafolio** [bakpakin/binser#16]
Hi,

I am trying to use binser to serialize data from lua. Based on the readme, it looks perfect, as I need to be able to include binary data into the files. That said, I have no clue how to do that, based on the readme I'd guess that I'd use `registerResource` to achieve that but I can't really make sense of it based on the readme. Can someone provide me with a full example of how to do that i.e. with an image?

Thank you!

**Comment by bakpakin** [comment]
Resources are just Lua values that are not serialized, instead a placeholder string is written. When the written string is deserialized, that string tells binser to return a reference to the resource. This is just a simple mechanism for values that cannot be serialized to be passed around. 

What specifically are you trying to serialize? Lua userdata? In that case, you will need to use plain old register and custom serialize and deserialize functions.

 ```lua
function writeMyImage(myImage)
  return myImage.asString()
end

function readMyImage(str)
  return myImageFromString(str)
end

binser.register(getmetatable(someImage), 'my.image.type', writeMyImage, readMyImage)
```

The above is just an example for a hypothetical image class

**Comment by mokafolio** [comment]
Thank you. I intend to retrieve a blob of binary data from the native application (it's basically a document tree, think SVG, in binary form), that will be saved alongside Lua data. Your image example is exactly what I was looking for and should get me started, thank you!
