### ISSUE TITLE
Lua 5.3 supported ?

### ISSUE THREAD

**Issue by hriekehof** [bakpakin/binser#17]
Hi,

i tried today the binser but i get this error message: `(number has no integer representation)`
So my table contains a few floating point values since can distinguish between them since lua 5.3. 
Is Lua 5.3 fully supported with floating point values ?

**Comment by bakpakin** [comment]
Lua 5.3 should be supported, as well as floating point numbers. What input is causing the error?

**Comment by hriekehof** [comment]
sorry for the late reply. I ran binser in on an embedded system where the lua interpreter is compiled for 32-bit float values. Could this be an issue ? I tried running it in on my desktop and there it worked fine. But this is a 64-Bit version.
I'll make another quick test tomorrow.

**Comment by bakpakin** [comment]
Yes, binser assumes ieee-754 doubles for numbers. The code could probably be modified to work properly when Lua numbers were 32 bit floats, but keep the format the same. We need to assume the format of numbers precisely to encode them efficiently and with the appropriate precision.

**Comment by hriekehof** [comment]
ah ok. Yeah then this is the issue for sure. If you plan to support 32-bit floats it would be great for me :) Otherwise i unfortunately cannot use binser
