### ISSUE TITLE
deserialing not have instruction

### ISSUE THREAD

**Issue by dj--alex** [bakpakin/binser#19]
Please add instruction to this function, i waste 3 days to find a way to DECODE serialized files.

Writing is simple
 local mydata = binser.serialize(uammokey,uicekey,ubombkey,udropkey,uleftkey,urightkey,uupkey,udownkey)
 sourcewrite(mydata, "keyboardsettings");  

But READING is real hardcore.
 keyboardloadingdata=sourceread ("keyboardsettings");  
 if (keyboardloadingdata~=0) then 
 ua= binser.deserialize (keyboardloadingdata) 
  uammokey =ua[1];--split("!") ;
  uicekey = ua[2];
  ubombkey = ua[3];
  udropkey = ua[4];
  uleftkey = ua[5];
  urightkey = ua[6];
  uupkey = ua[7];
  udownkey = ua[8];
  uunpackkey = ua[9];
end

i tries reads data wrong methods like this
 uammokey, uice, ubomb,uleft...= ua

**Comment by bakpakin** [comment]
well this has been sitting here a while, but not a bug. You clearly didn't read the documentation.
