### ISSUE TITLE
deserialize Registerd Class example ?

### ISSUE THREAD

**Issue by creekpld** [bakpakin/binser#4]
Can someone please provide an example how to deserialize the Employee "joe" metatable in the example on Templates.
I don't get it. (^_^;)

**Comment by bakpakin** [comment]
Templates are simply an optimization: the serialization and deserialization shouldn't change at all.

The point of templates is to not serialize the metatable or known keys at all. Lets say you have hundreds of employees, each with a name, salary, and age. If we serialize them one at a time, we would also serialize the strings 'name', 'salary', and 'age' hundreds of times (serializing them all at once is preferable if it can be done).

An object that has been registered to template is serialized and deserialized in the same way as any other object. The template optimization can be added as an optimization from smaller files.

To simplify the example:
```lua
-- Define a metatable from employees that implements a binser template
local Employee_MT = {
    name = 'employee', -- The unique name is required to uniquely identify the employee class
    _template = { -- binser looks for the '_template' key in the metatable
        "name", "age", "salary", "email" -- All employees should have a name, age, salary, and email.
    }
}

-- Make Joe
local joe = setmetatable({
    name = 'joe',
    age = 34,
    salary = '$1',
    email = 'example@example.com'
}, Employee_MT)

-- joe, and any other employee, can be serialized and deserialized like any other Lua value.
-- joestring is shorter, however, than it would have been without the template.
local joestring = binser.s(joe)
local joeCopy = binser.dn(joestring)
```

**Comment by creekpld** [comment]
Thanks,  apparently the key was using  binser.dn(joestring) instead of  binser.d(joestring).
 xD
