### ISSUE TITLE
Library not working in 5.3 version due to deprecated math functions

### ISSUE THREAD

**Issue by iganinja** [bakpakin/binser#5]
Hi

I am trying to use binser in my hobby project with Lua 5.3. It is failing as math.frexp() and math.ldexp() no longer exist in 5.3 version, as they are deprecated. Is there any plan to update binser to 5.3?

Thank you very much.

**Comment by bakpakin** [comment]
I can work on it, no problem. The only thing that is really needed is a pure lua implementation of math.frexp

**Comment by bakpakin** [comment]
Ok, I've made some fixes so that tests pass for Lua 5.3. Check them out on the master branch.

**Comment by iganinja** [comment]
Hi bakpakin

I downloaded the lastest version and pow is also missing, I think it was deprecated when operator ^ was added to Lua.

**Comment by bakpakin** [comment]
Interesting. It was passing Travis tests, though.

**Comment by bakpakin** [comment]
There are some other cases that I hadn't thought of when extending to 5.3 as well as deprecated functions. The new 64 bit integer type means that very large integers will not currently be serialized correctly, as binser will be attempt to encode them as double precision floats. I'm currently working on adding support for 64 bit integers.

**Comment by bakpakin** [comment]
Try the master branch now, it should be working correctly (fingers crossed). The missing math.pow function, however, is something that my local version of lua 5.3 still has. Regardless, I added a polyfill for Lua 5.3 for math.pow using the ^ operator.

**Comment by iganinja** [comment]
It works, bakpakin. Thank you very much again for your great job! :+1:
