### ISSUE TITLE
Update deserialize/N doc

### ISSUE THREAD

**Issue by lzubiaur** [bakpakin/binser#6]
Hi,

Just to let you know that the doc for `deserialize` and `deserializedN` in the README are missing the `index` argument.

In README 
```local function deserialize(str)```

in the source 
```local function deserialize(str, index)```

For instance the following code will not work as expected if the user doesnt know about the second `index` argument.
```
binser.deserialize(love.filesystem.read('myfile.ser'))
```

**Comment by bakpakin** [comment]
Thanks, the docs have been updated.
