### ISSUE TITLE
Priting a serialized table gives unicode symbols

### ISSUE THREAD

**Issue by kilbith** [bakpakin/binser#8]
Sorry for the very stupid question. I'm trying to print a simple table like so : 

```Lua
grid = {}
for i = 1, x do
for j = 1, y do
        grid[i] = {}
	grid[i][j] = 1
end
end

print(binser.s(grid))
```

All this gives as an output is  : 
```
�+�'�'�'�'�'�'�'�'�'�'�'�'�'�'�'�'
```

What I'm doing wrong?

**Comment by bakpakin** [comment]
This is what is supposed to happen. The serialized table is not human readable, it is machine readable. For a human readable string, use inspect.lua, ser.lua, or similar library.
