### ISSUE TITLE
fairly simple issue

### ISSUE THREAD

**Issue by mrfrigidaire** [bakpakin/binser#9]
Good day, 
This currently fairly simple code will return me an error when I try to to deserialize.

```
binser = require "includes/binser"
local player = {}
--
function love.load()
    if love.filesystem.exists( 'Save.lua' ) then
        player = binser.d(love.filesystem.load('Save.lua'))
    else
        player[1] = "foo"
        player[2] = "bar"
    end
end
--
function love.quit()
   love.filesystem.write( 'Save.lua', binser.s(player) )
end
```
actual error:
![binsererror](https://user-images.githubusercontent.com/36506563/36258595-e74beaa0-1263-11e8-9db1-e51b1bad4358.png)
content of save file:
![binsererror2](https://user-images.githubusercontent.com/36506563/36258629-10b4b642-1264-11e8-8f4d-49971c9ee0fe.png)

Thank you.

**Comment by bakpakin** [comment]
The string generated by binser is not Lua. It is not even valid text.
